# -*- coding: utf-8 -*-
"""KodePosPintar_Sukses.ipynb. 10 mei

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdsE0JNojqjHZkH1NpExlgIuFN9VpiGy

# KodePos Pintar: Web Sederhana di Google Colab
Rekomendasi lokasi tinggal berdasarkan gaya hidup. Dibuat dengan Python + Streamlit dan dijalankan lewat ngrok di Colab.
"""

# Install Streamlit dan ngrok
!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("KodePos Pintar")
# 
# keramaian = st.selectbox("Suka lingkungan seperti apa?", ["Ramai", "Tenang"])
# transport = st.selectbox("Butuh akses ke transportasi umum?", ["Ya", "Tidak"])
# sekolah = st.selectbox("Perlu dekat sekolah/kampus?", ["Ya", "Tidak"])
# taman = st.selectbox("Suka aktivitas di taman?", ["Ya", "Tidak"])
# 
# data = [
#     {"kode": "76111", "nama": "Daerah Prapatan dan Telaga Sari", "keramaian": "Ramai", "transport": "Ya", "sekolah": "Ya (SD 009 & 014, SMP NKPS, SMA Kartika V-I", "taman": "Ya, Wiluyo Puspo"},
#     {"kode": "67890", "nama": "Daerah B", "keramaian": "Tenang", "transport": "Tidak", "sekolah": "Ya", "taman": "Ya"},
#     {"kode": "54321", "nama": "Daerah C", "keramaian": "Tenang", "transport": "Ya", "sekolah": "Tidak", "taman": "Ya"},
# ]
# 
# if st.button("Cari Rekomendasi"):
#     best_match = None
#     best_score = -1
#     for area in data:
#         score = sum([
#             area["keramaian"] == keramaian,
#             area["transport"] == transport,
#             area["sekolah"] == sekolah,
#             area["taman"] == taman
#         ])
#         if score > best_score:
#             best_score = score
#             best_match = area
# 
#     if best_match:
#         st.success(f"Rekomendasi: {best_match['nama']} (Kode Pos: {best_match['kode']})")
#         st.write(f"Karakteristik: {best_match['keramaian']}, Transport: {best_match['transport']}, Sekolah: {best_match['sekolah']}, Taman: {best_match['taman']}")
#     else:
#         st.warning("Tidak ditemukan lokasi yang cocok.")

# Jalankan Streamlit dengan ngrok
from pyngrok import ngrok
import threading
import time
import os

ngrok.set_auth_token("2wuGpRM9RF2HynCyfggrSUZaQ7j_21Jm4tyYdwsjBRDbDNywV")

def run():
    os.system("streamlit run app.py")

thread = threading.Thread(target=run)
thread.start()

time.sleep(5)  # tunggu server hidup
public_url = ngrok.connect(8501)
print("Buka aplikasi kamu di sini:", public_url)